name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below.

  - type: dropdown
    id: site
    attributes:
      label: Website
      description: Which website would this feature apply to?
      options:
        - Kalshi.com
        - New site (please specify)
        - All sites / Global
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem would this feature solve?
      placeholder: Describe the current limitation or pain point
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: Describe any alternative approaches you've thought of

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here, including mockups or screenshots if helpful
